require('keybindings')
require('plugins')
require('settings')
require('colorscheme')
require('plugin-config/nvim-tree')
require('plugin-config/bufferline')
require('plugin-config/nvim-treesitter')
require('plugin-config.lualine')
require('plugin-config.indent-blankline')
require('plugin-config.telescope')
-- 内置LSP
require('lsp.setup')
